kind: Service
apiVersion: v1
metadata:
  name: webapp-svc-lb
  namespace: final
spec:
  selector:
    name: simple-webapp-mysql
  type: LoadBalancer
  ports:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 81
